### PR TITLE
Add qa to manifest

### PR DESCRIPTION
**Pull request by robyoung**

### CODE REVIEW

**Comment by quis** [comment]
:+1:

**Comment by TheDoubleK** [comment]
Should this be a major version bump as it will require an update to schemas in the API before it can be used?

**Comment by quis** [comment]
I don’t think so. You could upgrade now without breaking anything. It’s just some extra work to do to _use_ the new feature.

**Comment by TheDoubleK** [comment]
But if you upgrade the content on the frontend then trying to save answers for qualityAssurance will break because they don't exist in the API, won't they?

**Comment by quis** [comment]
That is true. Makes pretty much everything a breaking change though.

**Comment by TheDoubleK** [comment]
Yep.  Pretty much everything in content is :/

**Comment by pcraig3** [comment]
<sub>[oh whoops](https://github.com/alphagov/digitalmarketplace-frameworks/pull/121/files)</sub>

**Pull request merged**
