### PR TITLE
Update logic for subcontracting questions

### PR DESCRIPTION
**Pull request by bjgill**
Trello: https://trello.com/c/Oqg9AUup/328-3-update-conditional-logic-for-declaration-question-q53-for-dos5

CCS wanted us to make some changes to this question for DOS 5. If a supplier says they use subcontractors, show them two additional questions.

We've manually checked that the questions seem to appear when expected.

Known issues outstanding (to solve in future PRs):
1. The number field isn't being validated
2. The grey bar next to the second condition question is over-long
3. We don't yet know what the pass condition is (if any) for the two new questions

image

### CODE REVIEW

**Comment by lfdebrux** [comment]
### My review checklist

I've:

- [ ] looked at the code
- [ ] tested locally
- [ ] run functional tests locally

**Review by lfdebrux — APPROVED** [review]
Looks good to me

**Comment by bjgill** [comment]
Rebased. I'll merge once Travis gives us the green light

**Comment by lfdebrux** [comment]
I've just noticed an issue with that I didn't pick up earlier, sorry.

When I answer with one of the options that reveal the followup, I can't then go back and change my answer to an option that doesn't reveal the followup, as the validation complains that an answer is required to the followup questions.

**Comment by lfdebrux** [comment]
Actually now I can't answer at all without answering the follow up questions (using the main branch) 😟

**Comment by lfdebrux** [comment]
Oh wait, I had a brain fart, I forgot that the validator has to be updated. I knew that!

**Pull request merged**
