### PR TITLE
Update hint content for awarded contract value

### PR DESCRIPTION
**Pull request by CrystalPea**
Trello ticket: https://trello.com/c/zNCy9jwG/869-change-help-text-for-contract-value

### CODE REVIEW

**Comment by MuriloDalRi** [comment]
👍

**Comment by idavidmcdonald** [comment]
Needs a DOS1 file too

**Comment by idavidmcdonald** [comment]
And a version bump

**Comment by CrystalPea** [comment]
Thank you @idavidmcdonald, this has been done now 😁

**Comment by idavidmcdonald** [comment]
Were we going to make any changes to the validation message also? I know it's not defined in the story but worth getting this all double checked with Constance if not done already

**Comment by CrystalPea** [comment]
Wow, you are absolutely right, it would make a lot of sense to check validation message, too! I will look for Constance when i arrive at the office after lunch.

**Comment by idavidmcdonald** [comment]
Version bump needs to be in a separate commit - have a read of the readme instructions for more detail https://github.com/alphagov/digitalmarketplace-frameworks#versioning

**Comment by CrystalPea** [comment]
@idavidmcdonald Thanks for the link, I fixed that now and version bump is on a separate commit.

**Pull request merged**
