### PR TITLE
Minor typos

### PR DESCRIPTION
**Pull request by galund**
https://trello.com/c/qy16PFvR/289-52-what-is-your-organisation-s-duns-number
https://trello.com/c/tGhKRxb9/293-service-questions-terms-and-conditions-document-remove-full-stop
https://trello.com/c/ZpPRw8Pf/292-browser-client-side-app-question-wording

### CODE REVIEW

**Comment by TheDoubleK** [comment]
Will need a version bump too.  :+1: with that.

**Comment by samuelhwilliams** [comment]
Sensational work 👍

**Comment by galund** [comment]
I've never been more proud of my work than this day

**Comment by TheDoubleK** [comment]
Ha! Make that 6.4.8

**Pull request merged**
