### PR TITLE
add initial default.nix

### PR DESCRIPTION
**Pull request by risicle**
Much like all the other initial default.nix PRs.

### CODE REVIEW

**Comment by galund** [comment]
I don't really like that all these have so much boilerplate / copy-pasta. Is there anything we can do to reduce that?

**Comment by risicle** [comment]
Without creating yet another common repo and pulling in dependencies from it, not really.

**Comment by galund** [comment]
Could they be in a repo that's already common across all the apps that this is being duplicated in. dm-utils maybe?

**Comment by risicle** [comment]
It *could* but then we'd have to specify a certain *version* of that other repo, and that version wouldn't necessarily match the version that the main app depended on - we'd need to keep them in sync...

**Pull request merged**
