### PR TITLE
Updated 'view region' to 'view location' and fixed links.

### PR DESCRIPTION
**Pull request by danielknell**
Text changes to bring things inline with #323 and fixes the security issue with links for DOS questions.

Fixes https://www.pivotaltracker.com/n/projects/1884593/stories/134137657

### CODE REVIEW

**Comment by allait** [comment]
Should we be changing service questions for DOS-1? It's been closed for a while now and there's no way to view those question descriptions now. So the new description doesn't match what all of the suppliers have seen.

**Comment by TheDoubleK** [comment]
Yep I'd be tempted to only update the `/briefs/` questions that are still being displayed to users.  The `/services/` ones it feels like we should leave how they were.

**Comment by danielknell** [comment]
have nuked the commit updating dos entries, and just left the briefs one in place.

**Comment by TheDoubleK** [comment]
:+1: after a rebase. Sorry it took a while to get back to this :(

**Comment by idavidmcdonald** [comment]
It looks like we forgot to include a version bump for this pull request. One can be added retrospectively however by submitted a pull request with just the version bump.

**Pull request merged**
