### PR TITLE
Update supplier dec content

### PR DESCRIPTION
**Pull request by sarahonetui**
Updates to content based on feedback from CCS.

### CODE REVIEW

**Comment by quis** [comment]
Looks good to me.

**Comment by quis** [comment]
Can you [edit VERSION.txt here](https://github.com/sarahonetui/digitalmarketplace-frameworks/blob/update-supplier-dec-content/VERSION.txt) to be `0.3.1`?

**Comment by TheDoubleK** [comment]
Are the questions `subcontractorInformation1` and `subcontractorInformation2` still specific to subcontractors?  It looks like they have been made more generally applicable, in which case the names of the files (and so the keys for the saved information) should probably change to not mention `subcontractor`.

**Comment by sarahonetui** [comment]
Good point Kev, have renamed them. Thanks

**Comment by quis** [comment]
:+1:

**Pull request merged**
