### PR TITLE
Clone G11 from G10

### PR DESCRIPTION
**Pull request by katstevens**
Trello: https://trello.com/c/gJ6QDRRO/331-clone-g11-content-in-frameworks-repo

A basic clone of the G10 content, with a find-and-replace on `G-Cloud 10` -> `G-Cloud 11`. Everything in here will eventually be checked by a content designer. All dates, links etc are fictional and will be changed later.

Only a minor bump as the addition of this content shouldn't be a breaking change in itself.

### CODE REVIEW

**Comment by lfdebrux** [comment]
Should the version bump come after the find and replace?

**Comment by katstevens** [comment]
I don't think it really matters - the release is going to get tagged when the whole thing is merged...

**Comment by katstevens** [comment]
Looking back at the last clone we did, I'm going to add a commit to put the dates into the far future to make sure we change them later.

**Comment by katstevens** [comment]
Also added in `following_framework` - see commit message for details.

**Pull request merged**
