### PR TITLE
Updates to 'capped time and materials' description

### PR DESCRIPTION
**Pull request by tombye**
As requested in this story: https://www.pivotaltracker.com/story/show/118286875

### CODE REVIEW

**Comment by TheDoubleK** [comment]
`If the supplier finishes the work before they said they would, you still have to pay the full amount.` - this makes it sound just like a fixed price.

**Comment by sarahonetui** [comment]
The difference is the price is given in day rates and so should have less extra risk (cost) added by the supplier than in a fixed price contract. That said, I agree with you, they're very similar. It's one of the price options in the framework so we have to include it.

**Comment by TheDoubleK** [comment]
Might it make the difference more obvious to say something like `If the supplier finishes the work before they said they would, you only have to pay the amount for the time they have taken.` - or is that not true?
In which case could it be:  `If the supplier finishes the work before they said they would, you still have to pay the full amount specified in their original quote`?

It just feels like it need a few more words to make the difference clearer either way.

**Comment by sarahonetui** [comment]
The first statement isn't true, you have to pay the amount you capped the work at even if they finish early. Agreed with @TheDoubleK that probably best to leave as it is.

**Comment by TheDoubleK** [comment]
:+1:

**Comment by tombye** [comment]
Just to be clear, are these changes ok to be merged or does 'leave it as it is' mean to close this?

**Comment by sarahonetui** [comment]
Sorry. To be clear, we're going with the new content as it was in the story.

**Pull request merged**
