### PR TITLE
G12 file upload guidance

### PR DESCRIPTION
**Pull request by katstevens**
https://trello.com/c/Rtcc6oi6/316-add-link-to-guidance-on-making-accessible-pdfs-on-application-5-places

We want to provide suppliers with guidance on uploading accessible documents.

Paired with @NoraGDS on the content.

There are 6 questions that involve file uploads:

1) Modern Slavery Statement (for suppliers with < £36m turnover) 
2) Modern Slavery Statement (for suppliers with >= £36m turnover)
3) Service definition document
4) Terms and conditions document
5) SFIA rate card 
6) Pricing document

### Screenshot for 1 (Q2 is very similar):
pdf-guidance-modern-slavery

### Screenshot for 3 (Q4, 5 and 6 are very similar): 
pdf-guidance-service-def-doc

### CODE REVIEW

**Comment by risicle** [comment]
I'd love if we could say PDF/A-1, because we certainly shouldn't be accepting e.g. PDF/A-3

**Comment by katstevens** [comment]
> I'd love if we could say PDF/A-1, because we certainly shouldn't be accepting e.g. PDF/A-3

@NoraGDS - what do you think? The linked guidance doesn't mention what PDF/A-1 is anywhere...

**Comment by NoraGDS** [comment]
while I can see it would help with embedding files of any type - it may be confusing because the GDS guidance doesn't refer to the levels of PDF/A or how to produce them. Suggest for this framework we keep it consistent with the guidance.

**Comment by katstevens** [comment]
I've created a tech debt card to capture this for DOS5: https://trello.com/c/EijTv0m8/1287-provide-more-guidance-on-what-constitutes-a-pdf-a-1-opposed-to-pdf-a-2-a-3-etc

@risicle Are you ok with that for now?

**Comment by risicle** [comment]
Well, if we're going to start rejecting PDFs, we should at least let them know accurately what we *will* accept. Just saying PDF/A gives us much less grounds to reject a PDF/A-3 that they then give us.

**Pull request merged**
