### PR TITLE
Add file extension for new questions and add markdown spacing

### PR DESCRIPTION
**Pull request by TheDoubleK**

### CODE REVIEW

**Comment by tombye** [comment]
👍

**Comment by tombye** [comment]
@TheDoubleK can you change the name of this pull request?

**Comment by TheDoubleK** [comment]
Name changed - did you mean because I've added the new commit with spacing changes too?
Still good to go with those changes?

**Comment by tombye** [comment]
Yeah, exactly that, thanks 👍

**Pull request merged**
